repos:
  - repo: local
    hooks:
      - id: commit-check
        name: commit check (format and types)
        entry: make commit-check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-commit]

      - id: pre-push-check
        name: push check (format, types, and tests)
        entry: make pre-push-check
        language: system
        pass_filenames: false
        always_run: true
        stages: [pre-push]
