"""l1 identity session tables

Revision ID: 202605290001
Revises: 202605280004
Create Date: 2026-06-09 09:31:31.890143
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

from app.core.config import get_settings

revision: str = "202605290001"
down_revision: str | None = "202605280004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # citext (case-insensitive email) must exist before the users.email column is
    # created. Alembic autogenerate never emits CREATE EXTENSION, so this is manual.
    op.execute("CREATE EXTENSION IF NOT EXISTS citext")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_events",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("event_type", sa.Text(), nullable=False),
        sa.Column("actor_type", sa.Text(), nullable=False),
        sa.Column("actor_id", sa.UUID(), nullable=True),
        sa.Column("occurred_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column(
            "metadata", postgresql.JSONB(astext_type=sa.Text()), server_default=sa.text("'{}'::jsonb"), nullable=False
        ),
        sa.Column("request_id", sa.Text(), nullable=True),
        sa.CheckConstraint("actor_type IN ('user', 'system', 'admin')", name=op.f("ck_audit_events_actor_type")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_audit_events")),
    )
    op.create_index("ix_audit_events_actor_id_occurred_at", "audit_events", ["actor_id", "occurred_at"], unique=False)
    op.create_index(
        "ix_audit_events_event_type_occurred_at", "audit_events", ["event_type", "occurred_at"], unique=False
    )
    op.create_table(
        "rate_limit_buckets",
        sa.Column("bucket_key", sa.Text(), nullable=False),
        sa.Column("tokens", sa.Numeric(), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.PrimaryKeyConstraint("bucket_key", name=op.f("pk_rate_limit_buckets")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", postgresql.CITEXT(), nullable=False),
        sa.Column("password_hash", sa.Text(), nullable=True),
        sa.Column("role", sa.Text(), nullable=False),
        sa.Column("status", sa.Text(), nullable=False),
        sa.Column("mfa_enabled", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column("mfa_secret_encrypted", sa.LargeBinary(), nullable=True),
        sa.Column("terms_version_accepted", sa.Text(), nullable=True),
        sa.Column("terms_accepted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("disabled_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.CheckConstraint("role IN ('user', 'admin')", name=op.f("ck_users_role")),
        sa.CheckConstraint("status IN ('invited', 'active', 'disabled')", name=op.f("ck_users_status")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("email", name=op.f("uq_users_email")),
    )
    op.create_index("ix_users_status_role", "users", ["status", "role"], unique=False)
    op.create_table(
        "invitations",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_by_admin_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_admin_id"], ["users.id"], name=op.f("fk_invitations_created_by_admin_id_users")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_invitations_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_invitations")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_invitations_token_hash")),
    )
    op.create_index(
        "uq_invitations_active_per_user",
        "invitations",
        ["user_id"],
        unique=True,
        postgresql_where=sa.text("consumed_at IS NULL AND revoked_at IS NULL"),
    )
    op.create_table(
        "password_resets",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("consumed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("requested_ip", postgresql.INET(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_password_resets_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_password_resets")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_password_resets_token_hash")),
    )
    op.create_table(
        "refresh_tokens",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("token_hash", sa.Text(), nullable=False),
        sa.Column("parent_token_id", sa.UUID(), nullable=True),
        sa.Column("issued_at", sa.DateTime(timezone=True), server_default=sa.text("now()"), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("revoked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("revoked_reason", sa.Text(), nullable=True),
        sa.Column("user_agent", sa.Text(), nullable=True),
        sa.Column("ip", postgresql.INET(), nullable=True),
        sa.CheckConstraint(
            "revoked_reason IS NULL OR revoked_reason IN ("
            "'rotated', 'logout', 'password_reset', 'reuse_detected', 'account_disabled', '2fa_reset'"
            ")",
            name=op.f("ck_refresh_tokens_revoked_reason"),
        ),
        sa.ForeignKeyConstraint(
            ["parent_token_id"], ["refresh_tokens.id"], name=op.f("fk_refresh_tokens_parent_token_id_refresh_tokens")
        ),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], name=op.f("fk_refresh_tokens_user_id_users")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_refresh_tokens")),
        sa.UniqueConstraint("token_hash", name=op.f("uq_refresh_tokens_token_hash")),
    )
    op.create_index("ix_refresh_tokens_user_revoked", "refresh_tokens", ["user_id", "revoked_at"], unique=False)
    # ### end Alembic commands ###

    _seed_local_user()


def _seed_local_user() -> None:
    """Seed the V0.5 LOCAL_USER_ID as an active admin so existing owner-scoped rows
    map to a real user once the owner FKs land in the follow-up migration. Idempotent.

    Production (LOCAL_MODE=false, no LOCAL_USER_ID) starts on a fresh DB with no V0.5
    rows, so there is nothing to seed.
    """

    local_user_id = get_settings().local_user_id
    if local_user_id is None:
        return
    op.execute(
        sa.text(
            "INSERT INTO users (id, email, role, status) "
            "VALUES (CAST(:id AS uuid), :email, 'admin', 'active') "
            "ON CONFLICT (id) DO NOTHING"
        ).bindparams(id=str(local_user_id), email=f"local-{local_user_id}@local.invalid")
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_refresh_tokens_user_revoked", table_name="refresh_tokens")
    op.drop_table("refresh_tokens")
    op.drop_table("password_resets")
    op.drop_index(
        "uq_invitations_active_per_user",
        table_name="invitations",
        postgresql_where=sa.text("consumed_at IS NULL AND revoked_at IS NULL"),
    )
    op.drop_table("invitations")
    op.drop_index("ix_users_status_role", table_name="users")
    op.drop_table("users")
    op.drop_table("rate_limit_buckets")
    op.drop_index("ix_audit_events_event_type_occurred_at", table_name="audit_events")
    op.drop_index("ix_audit_events_actor_id_occurred_at", table_name="audit_events")
    op.drop_table("audit_events")
    # ### end Alembic commands ###
