"""BE-V0.5-16 trailing stop schema

Revision ID: 202605250001
Revises: 202605210001
Create Date: 2026-05-25 14:00:22.642702

Database-level surface for `trailing_stop_alert`
(docs/orders/v0.5/BE-V0.5-16-trailing-stop-alert.md §DB Schema). Evaluator,
command, Pydantic schema, and notification template land in later PRs — this
migration is structural only.

Generated by `alembic revision --autogenerate` for the column / nullable /
unique-index pieces. Hand-added on top:

1. Strategy enum extension. Baseline's `name="ck_trade_intents_strategy"` got
   double-prefixed by `target_metadata`'s naming convention, so the live DB
   constraint name is `ck_trade_intents_ck_trade_intents_strategy` (same gotcha
   202605210001 documented for trigger_events). Drop the doubled name and
   re-add the constraint under the clean `ck_trade_intents_strategy` with
   `trailing_stop_alert` added to the enum. Other trade_intents cks still
   carry doubled names — fixing them is intentionally out of scope for this
   work order, to keep the PR focused.

2. Six new structural cks: position_side / trail_mode enums, trail_value
   positivity, percentage upper bound (≤ 50), bidirectional
   trailing-vs-non-trailing field exclusivity (including target_price_*
   nullability gate), and position_side ↔ watermark side exclusivity.
   These are emitted via `op.create_check_constraint` with short names so
   the naming convention applies once, yielding clean `ck_trade_intents_<short>`
   names that match the model side.

Downgrade is symmetric. It will fail if any trailing rows exist when
restoring NOT NULL on target_price_* — acceptable: production never
downgrades, dev rebuilds from scratch.
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

revision: str = "202605250001"
down_revision: str | None = "202605210001"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


_NEW_TRADE_INTENT_CKS: list[tuple[str, str]] = [
    ("position_side", "position_side IN ('long', 'short')"),
    ("trail_mode", "trail_mode IN ('percentage', 'fixed_amount')"),
    ("trail_value_positive", "trail_value IS NULL OR trail_value > 0"),
    (
        "trail_value_percentage_upper",
        "trail_mode IS DISTINCT FROM 'percentage' OR trail_value <= 50",
    ),
    (
        "trailing_field_exclusivity",
        "("
        "  strategy = 'trailing_stop_alert'"
        "  AND position_side IS NOT NULL"
        "  AND trail_mode IS NOT NULL"
        "  AND trail_value IS NOT NULL"
        "  AND target_price_original IS NULL"
        "  AND target_price_effective IS NULL"
        ") OR ("
        "  strategy <> 'trailing_stop_alert'"
        "  AND position_side IS NULL"
        "  AND trail_mode IS NULL"
        "  AND trail_value IS NULL"
        "  AND target_price_original IS NOT NULL"
        "  AND target_price_effective IS NOT NULL"
        ")",
    ),
    (
        "watermark_side_exclusivity",
        "("
        "  position_side = 'long' AND watermark_low IS NULL"
        ") OR ("
        "  position_side = 'short' AND watermark_high IS NULL"
        ") OR ("
        "  position_side IS NULL"
        "  AND watermark_high IS NULL"
        "  AND watermark_low IS NULL"
        ")",
    ),
]


def upgrade() -> None:
    # --- autogen: trade_intents columns + nullable relaxations ---
    op.add_column("trade_intents", sa.Column("position_side", sa.Text(), nullable=True))
    op.add_column("trade_intents", sa.Column("trail_mode", sa.Text(), nullable=True))
    op.add_column("trade_intents", sa.Column("trail_value", sa.Numeric(precision=9, scale=4), nullable=True))
    op.add_column("trade_intents", sa.Column("watermark_high", sa.Numeric(precision=9, scale=4), nullable=True))
    op.add_column("trade_intents", sa.Column("watermark_low", sa.Numeric(precision=9, scale=4), nullable=True))
    op.add_column("trade_intents", sa.Column("dynamic_trigger_price", sa.Numeric(precision=9, scale=4), nullable=True))
    op.add_column(
        "trade_intents",
        sa.Column("watermark_updated_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "trade_intents",
        "target_price_original",
        existing_type=sa.NUMERIC(precision=9, scale=4),
        nullable=True,
    )
    op.alter_column(
        "trade_intents",
        "target_price_effective",
        existing_type=sa.NUMERIC(precision=9, scale=4),
        nullable=True,
    )

    # --- hand-added: strategy enum extension + doubled-prefix cleanup ---
    op.execute('ALTER TABLE trade_intents DROP CONSTRAINT "ck_trade_intents_ck_trade_intents_strategy"')
    op.create_check_constraint(
        "strategy",
        "trade_intents",
        "strategy IN ('buy_price_alert', 'sell_price_alert', 'trailing_stop_alert')",
    )

    # --- hand-added: trailing-only structural cks ---
    for short_name, condition in _NEW_TRADE_INTENT_CKS:
        op.create_check_constraint(short_name, "trade_intents", condition)

    # --- autogen: rewrite partial unique index with NULLS NOT DISTINCT ---
    op.drop_index(
        op.f("uq_trade_intents_active_duplicate"),
        table_name="trade_intents",
        postgresql_where="(status = ANY (ARRAY['scheduled'::text, 'active'::text]))",
    )
    op.create_index(
        "uq_trade_intents_active_duplicate",
        "trade_intents",
        [
            "owner_user_id",
            "symbol",
            "strategy",
            "position_side",
            "target_price_effective",
            "trail_mode",
            "trail_value",
            "quantity_lots",
            "trading_date",
        ],
        unique=True,
        postgresql_where=sa.text("status IN ('scheduled', 'active')"),
        postgresql_nulls_not_distinct=True,
    )

    # --- autogen: trigger_events trailing snapshot columns ---
    op.add_column(
        "trigger_events",
        sa.Column("watermark_at_trigger", sa.Numeric(precision=9, scale=4), nullable=True),
    )
    op.add_column(
        "trigger_events",
        sa.Column(
            "dynamic_trigger_price_at_trigger",
            sa.Numeric(precision=9, scale=4),
            nullable=True,
        ),
    )

    # --- hand-added: notifications type whitelist + intent-link extension ---
    # Trailing notifications use a new type that must be admitted by the
    # `notifications.type` CHECK; the trade_intent_id linkage invariant
    # (notification is always tied to an intent for the alert types) extends
    # symmetrically. Both constraints carry the doubled prefix from baseline
    # (`ck_notifications_ck_notifications_*`); replace in place rather than
    # rename, to keep the diff to a single migration boundary.
    op.execute('ALTER TABLE notifications DROP CONSTRAINT "ck_notifications_ck_notifications_type"')
    op.execute(
        'ALTER TABLE notifications ADD CONSTRAINT "ck_notifications_ck_notifications_type" '
        "CHECK (type IN ('price_triggered', 'trailing_stop_triggered'))"
    )
    op.execute('ALTER TABLE notifications DROP CONSTRAINT "ck_notifications_ck_notifications_price_triggered_intent"')
    op.execute(
        "ALTER TABLE notifications ADD CONSTRAINT "
        '"ck_notifications_ck_notifications_price_triggered_intent" '
        "CHECK (type NOT IN ('price_triggered', 'trailing_stop_triggered') "
        "OR trade_intent_id IS NOT NULL)"
    )


def downgrade() -> None:
    # --- hand-added reversal: restore baseline notifications cks ---
    op.execute('ALTER TABLE notifications DROP CONSTRAINT "ck_notifications_ck_notifications_price_triggered_intent"')
    op.execute(
        "ALTER TABLE notifications ADD CONSTRAINT "
        '"ck_notifications_ck_notifications_price_triggered_intent" '
        "CHECK ((type <> 'price_triggered') OR (trade_intent_id IS NOT NULL))"
    )
    op.execute('ALTER TABLE notifications DROP CONSTRAINT "ck_notifications_ck_notifications_type"')
    op.execute(
        'ALTER TABLE notifications ADD CONSTRAINT "ck_notifications_ck_notifications_type" '
        "CHECK (type IN ('price_triggered'))"
    )

    # --- autogen reversal: trigger_events columns ---
    op.drop_column("trigger_events", "dynamic_trigger_price_at_trigger")
    op.drop_column("trigger_events", "watermark_at_trigger")

    # --- autogen reversal: restore baseline partial unique index ---
    op.drop_index(
        "uq_trade_intents_active_duplicate",
        table_name="trade_intents",
        postgresql_where=sa.text("status IN ('scheduled', 'active')"),
        postgresql_nulls_not_distinct=True,
    )
    op.create_index(
        op.f("uq_trade_intents_active_duplicate"),
        "trade_intents",
        ["owner_user_id", "symbol", "strategy", "target_price_effective", "quantity_lots", "trading_date"],
        unique=True,
        postgresql_where="(status = ANY (ARRAY['scheduled'::text, 'active'::text]))",
    )

    # --- hand-added reversal: drop trailing-only structural cks ---
    # `op.f(...)` marks the name as final so the naming convention does NOT
    # prefix it a second time. Without it, `drop_constraint` would try to
    # drop `ck_trade_intents_ck_trade_intents_<short>` (doesn't exist).
    for short_name, _ in reversed(_NEW_TRADE_INTENT_CKS):
        op.drop_constraint(op.f(f"ck_trade_intents_{short_name}"), "trade_intents", type_="check")

    # --- hand-added reversal: restore baseline doubled-prefix strategy ck ---
    op.drop_constraint(op.f("ck_trade_intents_strategy"), "trade_intents", type_="check")
    op.execute(
        'ALTER TABLE trade_intents ADD CONSTRAINT "ck_trade_intents_ck_trade_intents_strategy" '
        "CHECK (strategy IN ('buy_price_alert', 'sell_price_alert'))"
    )

    # --- autogen reversal: restore NOT NULL on target_price_* ---
    op.alter_column(
        "trade_intents",
        "target_price_effective",
        existing_type=sa.NUMERIC(precision=9, scale=4),
        nullable=False,
    )
    op.alter_column(
        "trade_intents",
        "target_price_original",
        existing_type=sa.NUMERIC(precision=9, scale=4),
        nullable=False,
    )

    # --- autogen reversal: drop trailing columns ---
    op.drop_column("trade_intents", "watermark_updated_at")
    op.drop_column("trade_intents", "dynamic_trigger_price")
    op.drop_column("trade_intents", "watermark_low")
    op.drop_column("trade_intents", "watermark_high")
    op.drop_column("trade_intents", "trail_value")
    op.drop_column("trade_intents", "trail_mode")
    op.drop_column("trade_intents", "position_side")
