"""add owner_user_id fk to users

Revision ID: 202605290004
Revises: 202605290003
Create Date: 2026-06-09 15:48:29.080581
"""

from collections.abc import Sequence

from alembic import op

revision: str = "202605290004"
down_revision: str | None = "202605290003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(
        op.f("fk_notifications_owner_user_id_users"), "notifications", "users", ["owner_user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_trade_intents_owner_user_id_users"), "trade_intents", "users", ["owner_user_id"], ["id"]
    )
    op.create_foreign_key(
        op.f("fk_trigger_events_owner_user_id_users"), "trigger_events", "users", ["owner_user_id"], ["id"]
    )
    op.create_foreign_key(op.f("fk_twap_slices_owner_user_id_users"), "twap_slices", "users", ["owner_user_id"], ["id"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f("fk_twap_slices_owner_user_id_users"), "twap_slices", type_="foreignkey")
    op.drop_constraint(op.f("fk_trigger_events_owner_user_id_users"), "trigger_events", type_="foreignkey")
    op.drop_constraint(op.f("fk_trade_intents_owner_user_id_users"), "trade_intents", type_="foreignkey")
    op.drop_constraint(op.f("fk_notifications_owner_user_id_users"), "notifications", type_="foreignkey")
    # ### end Alembic commands ###
